### ISSUE TITLE
Donor address

### ISSUE THREAD

**Issue by yanrising** [MrFatoni/arb-claim#1]
Any solution for pay gas fee from donor address? If at hacked wallet wok autowithdrawal script its no sense

**Comment by MrFatoni** [comment]
no, sponsor gas currently only support at mainnet

**Comment by yanrising** [comment]
Thanks for comment. Any ideas how resolve this problem?

**Comment by MrFatoni** [comment]
most bots watching mempool transfer, i think by sending ETH through an internal transfer will beat the bot

check this [https://support.metamask.io/hc/en-us/articles/5716855323675-Fighting-back-against-sweeper-bots](https://support.metamask.io/hc/en-us/articles/5716855323675-Fighting-back-against-sweeper-bots)

**Comment by yanrising** [comment]
Great! Thanks for your help!
